version: '3'

services:
   app:
      build: ./

      container_name: 'prepise-back'
      image: prepise-back

      ports:
         - '8080:8080'

      links:
         - redis:redis

      environment:
         - REDIS_HOST=redis
         - REDIS_PORT=6379
         - NODE_ENV=production

      volumes:
         - 'D:/Site/JS/fullStack/Prepise/app/server:/data'

   redis:
      container_name: 'redis'
      image: redis:latest

      ports:
         - '6379:6379'

      volumes:
         - 'D:/Site/JS/fullStack/Prepise/app/server:/data'

      command: ['redis-server', '--bind', 'redis', '--port', '6379']
